name: new_notq_app
description: Flutter conversion of Kids Learning & Speech Therapy App (React/TS) with matched UI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  flutter_riverpod: ^2.3.6
  http: ^1.2.0
  record: ^6.1.1
  permission_handler: ^11.3.0
  path_provider: ^2.1.0
  camera: ^0.10.5
  web_socket_channel: ^3.0.0
  flutter_dotenv: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/nutq_app_logo.png
    - assets/images/google_icon.png
    - assets/images/profile_image.png
    - assets/images/app_logo.png
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/images/app_logo.png
    - .env
